### ISSUE TITLE
Inaccuracy - Wrong Country Displayed for Station

### ISSUE THREAD

**Issue by JeffHochberg** [EA7KDO/Nextion.Images#1]
I was in a QSO with a DMR station several days ago. They identified themselves as being located in the State of Georgia. Whenever they keyed up, the EA7KDO configuration on my Nextion display showed them as located in Guantanamo Bay, Cuba. I looked up their callsign on QRZ as well as on RadioID.net and they are most definitely located in Georgia. Is there a way I can debug this to determine where the inaccuracy stems from?

Configuration:
Pi-Star 4.1.0 RC6
Zumspot Raspberry Pi GPIO
Nextion 3.5" Enhanced display
EA7KDO NX4832K035.tft (November 2019 build)

Please let me know if you require any additional information. Feel free to reply here but I would also request that you send me a note via email using the address on my QRZ page. I do receive email notifications from GitHub but I receive a lot of them so it can be easy to miss the important ones and this one is important to me I want to help get to the bottom of this. :-)

https://www.qrz.com/db/W4JEW

Thanks and 73!

JeffH
Atlanta, GA
W4JEW

**Comment by KF6S** [comment]
Jeff,

 

If the station is transmitting talker alias and they do not put their call sign at the beginning of the talker alias field  it will break the flag/country lookup code and any flag and country can be displayed. It will return the flag/country that best matches the first few letters of their talker alias.  The most likely cause would be a talker alias containing letters KG4.  If you remember the call sign or talker alias of the station you were in QSO with I will test to make sure the code is not broken. 

 

else if(tolets2.txt=="KG4")//Guantanamo Bay (USA)

{

  p2.pic=246

  t202.txt="Guantanamo Bay (USA)"

 

 

73’s

Jim

KF6S

**Comment by KF6S** [comment]
Jeff,
It turns out the arm forces are still issuing KG4XX (two character suffix) to US stations in Guantanamo Bay, Cuba and the FCC is issuing KG4XXX (three character suffix) to stations in the US.  The code will need to be changed to handle this case. Thanks for pointing this out, I have now heard several KG4XXX calls on DMR.
73's
Jim
KF6S

**Comment by JeffHochberg** [comment]
Hi Jim,

Glad I could help out! I had the hotspot I experienced this issue on shut down as of a couple of days after the issue manifested itself. I powered it on earlier this evening to see if I was able to find the station's callsign in the logs since I forgot what it was, but it looked like Pi-Star already purged the entries.

Glad you were able to get to the bottom of it!

Any idea as to when you may release a new build of the configuration? Not that this is a a critical issue by any means. I'm just curious to see what you do next.

This is my most favorite Nextion display configuration yet! ABSOLUTELY AMAZING WORK!!!

-JeffH

**Comment by KF6S** [comment]
Mitch,

 

One more note on the statement below:

 

One other note.  The resultXX number is HEX so if you use a number such as
10 it would be coded as:  printh 0A and 11 would be coded as: printh 0B
etc.

If you are still having problems just send me the HMI.

 

The printh code is HEX but the result variables names are decimal so
result10.txt would be coded as printh 0A   and result11.txt would be coded
as printh 0B.

 

Jim

**Comment by KG4BEK** [comment]
Hello,
I came across this post and I am curious if you can help.
My call sign is KG4BEK and when I am using DMR, the hotspot identifies me as being in Guantanamo Bay.  I am located in the U.S.  Is there anyway for me to correct this? I have tried entering the longitude and latitude multiple times.  I have also tried reconfiguring the Talk Alias information.  I read the previous post were you mentioned entering the call sign first but I have not found anyway to change that.
Any help is appreciated.
Thank you,
Chris

**Comment by KF6S** [comment]
Chris,

 

Yes when this “flag” code was written the FCC was only giving out KG4 prefix to Guantanamo Bay (USA). When they opened up the K call sign area and started issuing any K combination to all USA licensed hams then this error and a few others like this were created.

If you want to email Mitch EA7KDO he is maintaining this code and he can update this for you when he does maintenance on the flag code.  Also if you send him a picture he may be able to add it to the next release so when it decodes your call your picture will be displayed.

 

Jim

 

 

  p2.pic=18

  t202.txt="GUAM"

}else if(tolets2.txt=="KG4")//Guantanamo Bay (USA)

{

  p2.pic=246

  t202.txt="Guantanamo Bay (USA)"

**Comment by KG4BEK** [comment]
Jim,
Thank you for this information! I was trying everything to correct the location on my display! I emailed Mitch and explained to him the situation.
Thanks for this info!
Chris

**Comment by KG4BEK** [comment]
Jim,I emailed Mitch several weeks ago, about my call sign identifying as being located in "Guantanamo Bay" but I never heard anything back from him.  The email that I used for Mitch was: ***@***.***  Do you know if this is his correct email?Thank you for your help!
Sincerely,Chris

KG4BEK
 
 
 
-----Original Message-----
